### ISSUE TITLE
Error when building on armhf (failed on RasPi2 and Odroid XU3)

### ISSUE THREAD

**Issue by phonikg** [cinemast/libjson-rpc-cpp#125]
I have in the past had no issue compiling from source on armhf, but have not been able to lately.  I have tried two scenario's with similar errors:

***Scenario 1:***
-I perform an `apt-get install libjsonrpccpp-dev libjsonrpccpp-tools` as per the debian instructions in README.md
-I then proceed to build 3rd party software(cpp-ethereum) that lists json-rpc-cpp as a dependency
-This build gets all the way to 100% and then throws the following error:

/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libjsonrpccpp-server.so: error: undefined reference to 'Json::Value::null'
collect2: error: ld returned 1 exit status
eth/CMakeFiles/eth.dir/build.make:122: recipe for target 'eth/eth' failed
make[2]: *** [eth/eth] Error 1
CMakeFiles/Makefile2:1446: recipe for target 'eth/CMakeFiles/eth.dir/all' failed
make[1]: *** [eth/CMakeFiles/eth.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

***Scenario 2***
-I decide to git clone jsonrpccpp and compile myself(confirming all dependencies have been installed)
-I receive the following error:

[ 29%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/abstractprotocolhandler.cpp.o
/home/eth/libjson-rpc-cpp/src/jsonrpccpp/server/abstractprotocolhandler.cpp: In member function 'void jsonrpc::AbstractProtocolHandler::ProcessRequest(const Json::Value&, Json::Value&)':
/home/eth/libjson-rpc-cpp/src/jsonrpccpp/server/abstractprotocolhandler.cpp:66:20: error: 'null' is not a member of 'Json::Value'
         response = Json::Value::null;
                    ^
src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/build.make:123: recipe for target 'src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/abstractprotocolhandler.cpp.o' failed
make[2]: *** [src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/abstractprotocolhandler.cpp.o] Error 1
CMakeFiles/Makefile2:180: recipe for target 'src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/all' failed
make[1]: *** [src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

***Any and all insight/help would be appreciated***
Also to assist you please let me know if there are any build logs i can run(and how to run them)

**Comment by cinemast** [comment]
Hi!

This is a known bug that was introduced by libjsoncpp to fix the ARM build. It is already fixed in Debian sid but due to the GCC5 transition, it might still take some time to land in testing.

For now, please install the package from sid manually: 
https://packages.debian.org/sid/libjsonrpccpp-dev
https://packages.debian.org/sid/libjsoncpp-dev

Another option would be to build the latest release of libjson-rpc-cpp on your own. I just cherry-picked the fix for it to master: https://github.com/cinemast/libjson-rpc-cpp/commit/fd8232fa95129d046511f3330b54c021063a45fb

Thank you for reporting this. Please close the issue if the problem has been fixed for you.

**Comment by phonikg** [comment]
@cinemast Thank You!! I am once again able to build from source and also install cpp-ethereum on armhf!

Cheers!

**Comment by cinemast** [comment]
Great to hear that :+1:
