### ISSUE TITLE
which example I should use to send and receive many data

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#132]
Dear All, 
I want to write a client/server application ton send and recieve many data ovet http
Could you please tell which json-rpc example I should use.
Thanks in advance

**Comment by cinemast** [comment]
Hi Nouri!

I appreciate that you find libjson-rpc-cpp an interesting project to work with. But I think we have a problem here:
You raised around 10 issues within the last days. Most of them could easily be solved with googling this or that. 
The issue tracker is mostly meant to track down errors (issues) within the project. If there is a bug, raise an issue. If there is clearly missing documentation, which cannot be reproduced from reading the source code, raise an issue.

But please don't raise an issue for every compile error you face, or an missing example. If you feel something is missing, contribute it and raise a pull-request. 

There are lots of people subscribed to this repository who are actually contributing to the project. They all get an email everytime you ask a question which is easily solved by googling. Also for general purpose questions on how to solve this or that, there is stackoverflow and the like.

I hope you understand my concerns and will think twice before raising an issue here again. I don't want to simply block you, because that is not the way I like to handle things here. 

Please reply here, especially if you think I am too harsh with you.

**Comment by Nouri1111** [comment]
there are no problem , and my question was simple and clear, and I want to contribute for this project

**Comment by cinemast** [comment]
Ok than. 

What exactly do you mean by "many data"?

There are ready to use jsonr-rpc server and client examples under src/examples.
