### ISSUE TITLE
[proposal] modular rpc server

### ISSUE THREAD

**Issue by debris** [cinemast/libjson-rpc-cpp#139]
Hi! Recently, when refactoring api layer of application that I'm working on, I came up with idea of rpc modules.

Proof of Concept implementation is available [here](https://github.com/debris/modular-libjson-rpc-cpp). What do you think about it @cinemast ? If you like it, I could integrate it 'properly' into libjson-rpc-cpp.

**Comment by cinemast** [comment]
That sounds very interesting. Personally I always had only 5 to 10 methods, but I get that this might be different in other projects.

Thank you for your input and also that you already provide code with it. I will have to take a deeper look at it, since I am a bit fuzzy on C++ templates.

Thanks, I'll get back to you.

**Comment by cinemast** [comment]
Hi @debris!

Sorry for taking so long to review this. I actually like the idea. If your offer still stands, I am looking forward to a pull request from you.

**Comment by debris** [comment]
Hi!

I'm glad that you liked it. My cpp skills got a bit rusty recently, but I will try to prepare a decent pr in next couple of weeks :)

**Comment by cinemast** [comment]
I will close this due to inactivity for now. Please just reopen a PR when ready.
