### ISSUE TITLE
Problem extending the RPC server

### ISSUE THREAD

**Issue by adah1972** [cinemast/libjson-rpc-cpp#183]
I have a special need to have a server that processes a few methods and forwards the rest. So the server does not keep all known method names. So far, I only see two approaches (either of which requires *modification* of libjson-rpc-cpp code):

- Add a new AbstractServer constructor: `AbstractServer(AbstractServerConnector &connector, IProtocolHandler* handler)`. Then I could clone `RpcProtocolServerV2` into an `RpcProtocolServerV2Ext` and modify its implementation, specifically the `HandleSingleRequest` part.
- Modify `RpcProtocolServerV2` to allow it to call an error handler when `ValidateRequest` fails.

With these changes, similar extensions would be easier in the future.

Do you have comments? I think the second approach is better, and would allow me to extend `RpcProtocolServerV2` without cloning its implementation. Do you agree and would like such a pull request, or do you have an alternative suggestion?

**Comment by cinemast** [comment]
Hi @adah1972. First, sorry for the late response.
@debris has suggested an even better approach in #139 I think but it got never properly integrated.
The current architecture does not allow for such scenarios. But I think it would be very interesting. 

I think the best way would be to allow several IClientConnectionHandler* in the AbstractServerConnector. This way we would not have to break current implementations.

So instead of the `setHandler()` method, we would add an `addHandler()` method to the AbstractServerConnector class.

**Comment by cinemast** [comment]
@adah1972 do you think you could prepare such a pull-request?

**Comment by cinemast** [comment]
@adah1972 this might get fixed in #211.

**Comment by adah1972** [comment]
#211 talks about allowing multiple `AbstractServerConnector`s in a single stub. Here you proposed allowing multiple `IProtocolHandler`s in a single `AbstractServerConnector`. I assume they are different?

**Comment by cinemast** [comment]
This was the initial proposal. Now we are working on having multiple `IProtocolHandler`'s per `AbstractServerConnector`.

**Comment by adah1972** [comment]
Would you please elaborate how that could solve the problem of extending `RpcProtocolServerV2`? I do not need/want to change the `HttpServer` part.

**Comment by adah1972** [comment]
Is the discussion going on outside #211? I do not see any mentions of `IProtocolHandler` there.

**Comment by mr-j0nes** [comment]
Hi there,

I am in the need of the same as requested in this post. I.e.: some methods are defined after the server is created. The second option described above by @adah1972 sounds like a very good way to achieve this:

- Modify `RpcProtocolServerV2` to allow it to call an error handler when `ValidateRequest` fails.

So whenever the called method is not found in the current server instead of returning an error it will call the handler, which will take over and try to process that method. If the method is also not found by the handler then the error is finally raised.

I took a look at the issue #211 but there they seem to be talking about a different subject i.e.: to accept the same requests from different type of connectors.. That means not other additional methods are added later but additional connectors.

Is my understanding correct ? Is what is requested in this post implemented already or planned to be implemented ?

Thanks in advance..

**Comment by cinemast** [comment]
@mr-j0nes could you take a look at the new implementation: https://github.com/jsonrpcx/json-rpc-cxx

Does the new API model solve your needs?

**Comment by mr-j0nes** [comment]
Thank you very much that library is a very nice piece of software. I just had to convert it from c++17 to c++14 to fit my project. 

I really appreciate it, Pity I didn't know about it before, it would have saved me some hours of development. Maybe you could have a link to that library on this one?. 

Yes indeed that API solve my needs.

**Comment by cinemast** [comment]
It is the top line in the README here: https://github.com/cinemast/libjson-rpc-cpp/blob/master/README.md.  Nice to hear it is useful for you.

**Comment by adah1972** [comment]
Since I am no longer working on this, and the need seems to have been satisfied elsewhere, I am closing this issue now.
