### ISSUE TITLE
Is Client::CallMethod thread-safe?

### ISSUE THREAD

**Issue by russdirks** [cinemast/libjson-rpc-cpp#187]
I have 2 threads, each with their own instance of an HTTP Client.  One thread makes requests to the server every 200ms, the other thread much less often.  I occasionally get errors like `libcurl error: 2`, or sometimes the program crashes with a report of heap corruption.  I'm running Windows 10.

Would it be advisable to have only one instance of the Client shared between the 2 threads, and use a mutex to enforce single usage?

**Comment by cinemast** [comment]
Could you share some code that can reproduce this? Actually it should be thread safe.

**Comment by russdirks** [comment]
I'm working on a fork of [Genoil's Ethereum ethminer program](https://github.com/Genoil/cpp-ethereum), which is fairly large, so posting code might not be feasible.  

But, I added some trace statements to my program and found that things are not quite the way I thought they were.  In actual fact, one instance of the HTTP Client can at times be access by two threads simultaneously, and when that happens, I get the error messages I mentioned.  Here's an example:

```
1.  d19 16:43:23.068> Trace: GenericFarm::setWork				[thread 1]
2.  d19 16:43:23.068> Trace: MinerRPC.getBlockNumber				[thread 1]
3.  d19 16:43:23.099> Trace: MinerRPC.peerCountCB				[thread 2]
4.  d19 16:43:23.130> Trace: GenericMiner::setWork, miner[0]			[thread 1]
5.  d19 16:43:23.130> Exception: MinerRPC.peerCountCB - Exception -32003 : Client connector error: libcurl error: 2

```

Both `getBlockNumber` and `peerCountCB` result in calls to the client `CallMethod` method, so that is where the concurrency is happening.

I'm going to use mutexes to protect against that, and I think that should solve the problem at my end.

**Comment by cinemast** [comment]
So are the to threads using each its own http client or not? I am not quite sure, because your fist post mentions two different http clients, but the second rather implies that only one instance of http client has been used.

To summarize, Using a single HttpClient in a multithread environment is not thread safe.
Creating multiple HttpClient's is thread safe, concerning [this](https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/client/connectors/httpclient.cpp#L20) section.

Please create a new StubClient for each thread.
