### ISSUE TITLE
Set MHD listening interface

### ISSUE THREAD

**Issue by metalicjames** [cinemast/libjson-rpc-cpp#200]
By default the MHD shipped with json-rpc-cpp listens on all interfaces. Is there a way to restrict it to just listen on localhost?

**Comment by cinemast** [comment]
For this I would suggest the [UnixDomainSocketServer](https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/server/connectors/unixdomainsocketserver.h)

**Comment by loreilei** [comment]
ALso if your platform do not support unix domain sockets, you can use a [TCPSocketServer](https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/server/connectors/tcpsocketserver.h) bound to localhost IP.

**Comment by domob1812** [comment]
I think this is a major drawback of libjson-rpc-cpp, at least for projects similar to what I'm doing (namely using JSON-RPC for inter-process communication).  Listening on all interfaces rather than just localhost is a major security issue in those cases, since I just want local communication within a machine.  Of course, a firewall could be used to block the port externally, but that just adds another possible error source with perhaps fatal consequences if missed.

The non-HTTP transports are also not really good options, since a) `UnixDomainSocketServer` presumably does not work well on Windows (and `TCPSocketServer` seems to have other issues) and b) JSON-RPC client libraries (other than libjson-rpc-cpp) are not easy to connect to those.

Is there a specific reason why there is not an option to listen locally, or has this "just not been implemented"?

**Comment by cinemast** [comment]
> Is there a specific reason why there is not an option to listen locally, or has this "just not been implemented"?

It is just that. I am happy to merge a PR

**Comment by domob1812** [comment]
> > Is there a specific reason why there is not an option to listen locally, or has this "just not been implemented"?
> 
> It is just that. I am happy to merge a PR

Cool, I was actually thinking of doing one (and have an unpolished proof-of-concept working already). :)
