### ISSUE TITLE
Websocket implementation

### ISSUE THREAD

**Issue by shutej** [cinemast/libjson-rpc-cpp#24]
...where both the client and the server talk to one another without reopening a socket per RPC.  I couldn't figure this out in 0.2.  If it can't yet be done in another way, I'd lobby for supporting WebSockets with the following test case:

https://github.com/Textalk/jquery.jsonrpcclient.js

WebSockets would be excellent because you could authenticate and connect once (both expensive operations) and chat more cheaply thereafter.

BTW, 0.2 works delightfully with a server I made with http://www.gorillatoolkit.org/pkg/rpc/v2 and http://www.gorillatoolkit.org/pkg/rpc/v2/json as long as:
1. You name the method YourGoStruct.YourExportedMethod in the .json schema file.
2. You call client->YourGoStruct_YourExportedMethod(...).
3. You carefully read the generated header to see that the arguments are lexicographically sorted.  :-)

Thanks for the great library!

Jeremy

**Comment by tnbailey** [comment]
Hi toolmmy, I have some questions about source at toolmmy@a89dda6
I have a couple of potential bugs to ask about:
1) static pointer declaration in isWebsocketConnection() becomes stale after several iterations causing failures to connect:
   bool WebsocketServer::isWebsocketConnection(struct mg_connection *connection)
        ... why is the below websocketVersion pointer declared static?
        static const char* websocketVersion = mg_get_header(connection, WS_HEADER_VERSION);
2) call to mg_close_connection() from RemoveConnection() causes seg fault the next time that worker_thread is used because the mongoose connection struct is freed in mg_close_connection:
    bool WebsocketServer::RemoveConnection(struct mg_connection* connection)
            ... should the below line be removed?
            mg_close_connection(it->conn);

**Comment by toolmmy** [comment]
Hi tnbailey,

thank's for bringing the attention back to this project. I will check 
for a solution based suggestions and keep you in touch.

Am 29.10.2015 um 22:56 schrieb tnbailey:

**Comment by ampyx** [comment]
@toolmmy @cinemast was this ever pulled into develop?

**Comment by cinemast** [comment]
No not yet. If there would be a proper pull request against dev, I will review it and consider to merge it.

**Comment by markos** [comment]
hi, really interested in getting json-rpc over websockets working, I'm evaluating this library for our server, is this still going to be implemented in libjson-rpc-cpp?
Thanks

**Comment by cinemast** [comment]
Websockets, currently no, but it works via AJAX.

**Comment by cinemast** [comment]
Additionally, JSON-RPC is not really meant to function bi-directional in general. It follows a request/response model.

**Comment by markos** [comment]
problem is we have an existing solution that does that -bi-directional json-rpc over websockets- for both backend (C++) and front-end in (JS) and we're looking to replace the existing solution that's quite old and buggy with a modern solution and json-rpc-cpp was one of the first suggestions. I'm going to try @toolmmy's code to see if it works, but still it would be nice to see it in the library itself.

**Comment by toolmmy** [comment]
@markos the fork is pretty old and is using moongoose. the current implementation of the library is using microhttpd instead. So there are major modifications required to bring it up to date.

**Comment by cinemast** [comment]
I don't think that a websocket implementation will end up here soon. If someone would actually implement it and deliver a PR, I would still have to make sure that it stays maintained (either by me or someone else commited to the project), otherwise I won't merge it due to future quality and bloating concerns.

However, on the bright side, the architecture of libjson-rpc-cpp is connector agnostic. You can derive from [AbstractServerConnector](https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/server/abstractserverconnector.h) and [IClientConnector](https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/client/iclientconnector.h) yourself to implement any other desired protocol. This does not even require a recompilation of os shipped versions of libjson-rpc-cpp.

I hope you understand my point of view on this.
